### ISSUE TITLE
display trajectories that drop below 1, dynamic y-axis

### ISSUE THREAD

**Issue by ole-peters** [SeloSlav/FarmersFable#1]
currently trajectories cut off at 1. We should show the full trajectory even when it's below 1. There seems to be an issue with setting the lower bound dynamically.

**Comment by ole-peters** [comment]
I think that's better, though still not dynamic -- how weird that that doesn't work. 

btw: shouldn't Bill start at 1kg as in the deterministic case? Is there an important reason for changing the initial wealth to ~12 kg?

Ah, it should be kg (little k) not Kg in the labels.

**Comment by SeloSlav** [comment]
We could use these icons instead:

![image](https://user-images.githubusercontent.com/8828948/57035797-bd6b2f80-6c07-11e9-95d1-84f6c26ccb94.png)

I suppose it's mostly assumed that prepending @ means we'll be linking to Twitter in any case.

**Comment by SeloSlav** [comment]
It actually does start at 1 kg in the equation, so now I'm wondering if there is something with the calculation for the labels. May be multiplying everything by some exponential factor?

Also if initial value is ~12 kg this means the chart begins by drawing tick 2. I can fix that.

**Comment by SeloSlav** [comment]
Found out why it started around ~12kg.

Since the growth equation is as follows

``log10(10^(tmpBill4*noise_bill3)``

I set the initial grain value to 0 instead of 1.

At 1 we have log10(10^(1)*1.5)) = 1.176 or log10(10^(1)*0.7)) = 0.845

10^1.176 = 15 or 10^0.845 = 7.

At 0 it is 1.5 or 0.7, which is what we expect.
