### ISSUE TITLE
1 kg line

### ISSUE THREAD

**Issue by Marcthewriter** [SeloSlav/FarmersFable#12]
Just a minor question:

Does the fatter line at 1 kg in all the graphs (here one example) make sense?

![Bildschirmfoto 2019-05-04 um 03 43 38](https://user-images.githubusercontent.com/50121811/57172580-56759280-6e22-11e9-867d-241a8ec5d622.png)

**Comment by SeloSlav** [comment]
I'll look at changing this but this seems to be an artifact of the way we decided to present the chart as linear-in-logs.

The 1kg is actually the 0 line, which is drawn by the charting library. 10^0 is 1 so that's where the line is displayed.

I agree it makes no sense but I am not hopeful it can be fixed.

**Comment by SeloSlav** [comment]
However, if the line is framed a "baseline" for where we started then perhaps that's useful?

**Comment by SeloSlav** [comment]
Saving this resource for later: https://stackoverflow.com/questions/45540041/remove-excess-lines-on-y-axis-using-chartjs

**Comment by SeloSlav** [comment]
Just following up on this. Is this a big issue? Because I don't think fixing this at the moment will be trivial. Our switch from the supported 'log type' chart is causing this issue, because the y axis is now mapping the exponents, and the code draws the line through the origin, 10^0 = 1 kg, by default.

There is a setting that allows me to remove ALL gridlines on the axis, but not to remove the gridline only at the origin.

Any thoughts?

@ole-peters?

**Comment by ole-peters** [comment]
You may be able to hack it, but I don't know the language. You could potentially draw all lines shifted up by 1,000 or so and just re-convert the labels. 

But I don't think it's a big issue, and given that 1kg is the baseline, I agree, people will probably think it's done on purpose :-)

**Comment by Marcthewriter** [comment]
Just thought I bring it up just in case we had dragged something with us we don't need any longer ... No big issue. As Ole writes :-) people will probably think it's done on purpose :-)

**Comment by SeloSlav** [comment]
I'm doing everything I can avoid actually opening the charting library itself and changing it at the moment, because I know that will be a rabbit hole. XD

![image](https://user-images.githubusercontent.com/8828948/57254267-b2e4d780-7005-11e9-9fc2-a3c6fe4e35ad.png)

One thing I noticed is that it is far less pronounced on graph's where both Bill and Ann have lines together (blue and red lines)

When I change the color to blue it is less noticeable.

**Comment by SeloSlav** [comment]
I'll mark this as closed and if I happen to find a solution soon will implement it.
